Add search bar
CathrinTruchan/capstone-project pull request #23
Opened 2022-10-25 14:02 UTC by CathrinTruchan

Hello :) 
I added a search bar to the index and the flow-page. I am looking forward to your feedback. Thanks :)

2022-10-25 14:59 UTC, F-Kirchhoff requested changes
Hey, I added some suggestions, I think you made it yourself much harder than it needed to be

2022-10-25 15:20 UTC, CathrinTruchan commented on pages/_app.js
> +        searchQuery={searchQuery}
Ah, of course. That's easier :) Thanks!

2022-10-25 15:48 UTC, CathrinTruchan commented
> Hey, I added some suggestions, I think you made it yourself much harder than it needed to be

Thanks a lot for reviewing @F-Kirchhoff! I added the changes you requested. Can you check the code again?

2022-10-26 08:20 UTC, F-Kirchhoff approved these changes
LGTM 🦊

2022-10-26 08:20 UTC, F-Kirchhoff commented on pages/index.js
> +            })
nice!

2022-10-26 08:31 UTC, CathrinTruchan commented
> LGTM 🦊

Thanks ✌️

2022-10-26 12:49 UTC, merged